### ISSUE TITLE
ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by JeromeGillard** [IBM/node-red-tensorflowjs#12]
When running Node-red within their latest Docker image, I got this error:
`22 Feb 16:19:18 - [error] [tfjs-object-detection:d4744fe3.2fbc6] Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /data/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node_modules/@tensorflow/tfjs-node/lib/napi-v5/../../deps/lib/libtensorflow.so.1)
`

Tried to fix it with `apk add libc6-compat` but no luck.

I can see that the lib is well on the image, within the container:
`bash-5.0# ls -al /lib64/ld-linux-x86-64.so.2
lrwxrwxrwx    1 root     root            26 Feb 22 15:28 /lib64/ld-linux-x86-64.so.2 -> /lib/libc.musl-x86_64.so.1
`
Any idea how to get it running?

**Comment by pvaneck** [comment]
Hey, I'm not familiar with the Alpine Linux, but likely the issue might be due to some underlying problem with tfjs-node or tensorflow. 

You can try: `export LD_LIBRARY_PATH=/lib64` to see if you get past the `No such file or directory` error, however you might encounter issues with the libtensorflow binary itself with symbols missing. There is an existing issue open in the tfjs repo: https://github.com/tensorflow/tfjs/issues/1425 , so I am wondering if you'll encounter the same.

**Comment by JeromeGillard** [comment]
Indeed, after linking  `ln -s /lib64/ld-linux-x86-64.so.2 /lib/ld-linux-x86-64.so.2` within the container, I've got the same issue than tensorflow/tfjs#1425.

`[error] [tfjs-object-detection:d4744fe3.2fbc6] Error: Error relocating /data/node-red-tensorflowjs/node-red-contrib-tfjs-object-detection/node_modules/@tensorflow/tfjs-node/lib/napi-v5/../../deps/lib/libtensorflow.so.1: __memcpy_chk: symbol not found`

Closing this issue, thanks for your support.
